In [2]:
!pip install nba_api
!pip install basketball_reference_web_scraper

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nba_api
  Downloading nba_api-1.1.14-py3-none-any.whl (254 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.9/254.9 KB 6.0 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.8/dist-packages (from nba_api) (1.22.4)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from nba_api) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->nba_api) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->nba_api) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->nba_api) (1.26.14)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->nba_api) (2.10)
Installing collected packages: nba_api
Successfully installed nba_api-1.1.14
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting basketball_reference_web_scraper
  Downloading basketball_reference_web_scraper-4.12.1-py3-none-any.whl (24 kB)
Collecting certifi==2018.10.15
  Downloading certifi-2018.10.15-py2.py3-none-any.whl (146 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.3/146.3 KB 5.3 MB/s eta 0:00:00
Collecting urllib3==1.24.3
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.8/118.8 KB 13.9 MB/s eta 0:00:00
Collecting requests==2.20.0
  Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 KB 8.5 MB/s eta 0:00:00
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 KB 18.9 MB/s eta 0:00:00
Collecting lxml==4.5.1
  Downloading lxml-4.5.1-cp38-cp38-manylinux1_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 68.0 MB/s eta 0:00:00
Collecting idna==2.7
  Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.2/58.2 KB 8.6 MB/s eta 0:00:00
Collecting pytz==2018.6
  Downloading pytz-2018.6-py2.py3-none-any.whl (507 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 KB 43.7 MB/s eta 0:00:00
Installing collected packages: pytz, idna, chardet, certifi, urllib3, lxml, requests, basketball_reference_web_scraper
  Attempting uninstall: pytz
    Found existing installation: pytz 2022.7.1
    Uninstalling pytz-2022.7.1:
      Successfully uninstalled pytz-2022.7.1
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: chardet
    Found existing installation: chardet 4.0.0
    Uninstalling chardet-4.0.0:
      Successfully uninstalled chardet-4.0.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2022.12.7
    Uninstalling certifi-2022.12.7:
      Successfully uninstalled certifi-2022.12.7
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.14
    Uninstalling urllib3-1.26.14:
      Successfully uninstalled urllib3-1.26.14
  Attempting uninstall: lxml
    Found existing installation: lxml 4.9.2
    Uninstalling lxml-4.9.2:
      Successfully uninstalled lxml-4.9.2
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.11.2 requires requests<3,>=2.21.0, but you have requests 2.20.0 which is incompatible.
google-colab 1.0.0 requires requests>=2.25.1, but you have requests 2.20.0 which is incompatible.
google-cloud-bigquery 3.4.2 requires requests<3.0.0dev,>=2.21.0, but you have requests 2.20.0 which is incompatible.
Successfully installed basketball_reference_web_scraper-4.12.1 certifi-2018.10.15 chardet-3.0.4 idna-2.7 lxml-4.5.1 pytz-2018.6 requests-2.20.0 urllib3-1.24.3

In [6]:
from basketball_reference_web_scraper import client
from basketball_reference_web_scraper.data import OutputType
from nba_api.stats.endpoints import playercareerstats
import json
import pandas as pd

PLAYER_JSON = client.players_season_totals(season_end_year=2023, output_type=OutputType.JSON)
total_t = json.loads(PLAYER_JSON)

PLAYER_stats = pd.json_normalize(total_t)

# get the players who play more than 30 minutes

Player_list_1 = PLAYER_stats[PLAYER_stats['minutes_played']/PLAYER_stats['games_played'] >= 30]

new_columns = ['name'] + ['minutes_played'] + ['games_played'] + ['points'] + ['team'] + [c for c in Player_list_1.columns if c not in ('name','minutes_played','games_played','points','team')]
Player_list_1 = Player_list_1[new_columns]

print(Player_list_1.columns)
Player_list_1 = Player_list_1.sort_values(by='points', ascending=False)
display(Player_list_1)

Index(['name', 'minutes_played', 'games_played', 'points', 'team', 'age',
       'assists', 'attempted_field_goals', 'attempted_free_throws',
       'attempted_three_point_field_goals', 'blocks', 'defensive_rebounds',
       'games_started', 'made_field_goals', 'made_free_throws',
       'made_three_point_field_goals', 'offensive_rebounds', 'personal_fouls',
       'positions', 'slug', 'steals', 'turnovers'],
      dtype='object')

,name,minutes_played,games_played,points,team,age,assists,attempted_field_goals,attempted_free_throws,attempted_three_point_field_goals,...,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,positions,slug,steals,turnovers
131,Luka Dončić,1930,53,1759,DALLAS MAVERICKS,23,428,1175,583,415,...,53,594,426,145,46,140,[POINT GUARD],doncilu01,79,192
493,Jayson Tatum,2166,58,1748,BOSTON CELTICS,24,272,1238,486,541,...,58,569,420,190,65,123,[POWER FORWARD],tatumja01,60,172
173,Shai Gilgeous-Alexander,1918,54,1674,OKLAHOMA CITY THUNDER,24,307,1091,574,139,...,54,553,521,47,48,145,[POINT GUARD],gilgesh01,89,155
150,Joel Embiid,1683,48,1584,PHILADELPHIA 76ERS,28,196,987,563,148,...,48,525,484,50,86,153,[CENTER],embiijo01,53,170
430,Julius Randle,2256,63,1582,NEW YORK KNICKS,28,259,1159,438,510,...,63,537,332,176,132,188,[POWER FORWARD],randlju01,42,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Kyrie Irving,258,7,173,DALLAS MAVERICKS,30,48,128,28,53,...,7,63,27,20,11,23,[POINT GUARD],irvinky01,7,14
65,Mikal Bridges,200,6,143,BROOKLYN NETS,26,19,95,31,32,...,6,50,28,15,8,11,[SMALL FORWARD],bridgmi01,8,11
129,Spencer Dinwiddie,238,7,119,BROOKLYN NETS,29,42,91,35,45,...,7,37,30,15,1,17,[POINT GUARD],dinwisp01,7,16
105,Mike Conley,185,6,51,MINNESOTA TIMBERWOLVES,35,35,49,5,30,...,6,18,4,11,4,9,[POINT GUARD],conlemi01,9,8
541,Russell Westbrook,93,3,48,LOS ANGELES CLIPPERS,34,28,34,8,9,...,3,18,8,4,3,11,[POINT GUARD],westbru01,7,13

Warning: Total number of columns (22) exceeds max_columns (20) limiting to first (20) columns.

In [9]:
PLAYER_advanced_JSON = client.players_advanced_season_totals(season_end_year=2023, output_type=OutputType.JSON)
advanced_total_t = json.loads(PLAYER_advanced_JSON)

PLAYER_advanced_stats = pd.json_normalize(advanced_total_t)
advanced_new_column = ['name'] + [c for c in PLAYER_advanced_stats.columns if c != 'name']
PLAYER_advanced_stats = PLAYER_advanced_stats[advanced_new_column]
PLAYER_advanced_stats = PLAYER_advanced_stats.sort_values(by='player_efficiency_rating', ascending=False)
print(PLAYER_advanced_stats.columns)

display(PLAYER_advanced_stats)

Index(['name', 'age', 'assist_percentage', 'block_percentage',
       'box_plus_minus', 'defensive_box_plus_minus',
       'defensive_rebound_percentage', 'defensive_win_shares',
       'free_throw_attempt_rate', 'games_played', 'is_combined_totals',
       'minutes_played', 'offensive_box_plus_minus',
       'offensive_rebound_percentage', 'offensive_win_shares',
       'player_efficiency_rating', 'positions', 'slug', 'steal_percentage',
       'team', 'three_point_attempt_rate', 'total_rebound_percentage',
       'true_shooting_percentage', 'turnover_percentage', 'usage_percentage',
       'value_over_replacement_player', 'win_shares',
       'win_shares_per_48_minutes'],
      dtype='object')

,name,age,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,defensive_rebound_percentage,defensive_win_shares,free_throw_attempt_rate,games_played,...,steal_percentage,team,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares,win_shares_per_48_minutes
513,Stanley Umude,23,0.0,43.8,48.4,32.7,0.0,0.0,2.000,1,...,24.1,DETROIT PISTONS,1.000,0.0,0.532,0.0,39.8,0.0,0.0,0.626
132,Tyler Dorsey,26,0.0,0.0,18.1,1.5,15.0,0.0,0.000,3,...,0.0,DALLAS MAVERICKS,0.400,14.7,0.900,0.0,28.3,0.0,0.1,0.373
49,Goga Bitadze,23,18.3,0.0,16.0,3.7,63.0,0.0,0.333,1,...,0.0,ORLANDO MAGIC,0.333,37.9,0.872,0.0,16.5,0.0,0.1,0.451
303,A.J. Lawson,22,0.0,0.0,5.3,7.6,54.8,0.0,0.000,1,...,0.0,MINNESOTA TIMBERWOLVES,0.000,28.0,1.000,0.0,21.3,0.0,0.0,0.381
495,Terry Taylor,23,0.0,0.0,8.6,4.0,0.0,0.0,0.000,1,...,0.0,CHICAGO BULLS,0.000,0.0,1.000,0.0,21.9,0.0,0.0,0.310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,Leandro Bolmaro,22,12.4,1.2,-14.9,-2.3,4.8,0.0,0.000,14,...,2.1,UTAH JAZZ,0.200,5.6,0.150,25.9,16.6,-0.2,-0.3,-0.229
474,Marko Simonovic,23,0.0,0.0,-21.7,-5.8,0.0,0.0,0.000,3,...,0.0,CHICAGO BULLS,1.000,0.0,0.000,0.0,8.8,0.0,0.0,-0.199
81,Deonte Burton,29,0.0,0.0,-24.8,-10.0,0.0,0.0,0.000,2,...,0.0,SACRAMENTO KINGS,0.500,0.0,0.000,0.0,14.3,0.0,0.0,-0.347
548,Alondes Williams,23,0.0,0.0,-26.6,-5.4,21.9,0.0,0.000,1,...,0.0,BROOKLYN NETS,0.000,11.4,0.000,100.0,17.8,0.0,-0.1,-0.521
281,Trevor Keels,19,0.0,0.0,-44.6,-8.4,100.0,0.0,0.000,1,...,0.0,NEW YORK KNICKS,1.000,54.1,0.000,0.0,42.9,0.0,0.0,-0.813

Warning: Total number of columns (28) exceeds max_columns (20) limiting to first (20) columns.